import{a as P,S as B,i}from"./assets/vendor--6n4cVRZ.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const x="54715064-755e6188e76709980fdae3ed5",M="https://pixabay.com/api/";async function m(o,a){return(await P.get(M,{params:{key:x,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:a}})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),f=document.querySelector(".loadMoreButton");let R=new B(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const a=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:t,views:l,comments:q,downloads:v})=>`<li class = "gallery-item">
        <a href = "${c}" class="gallery-link">
        <img src = "${s}" alt = "${e}" class="gallery-images"/>
        </a>
       <ul class="data-list">
  <li class="image-data"><p class="image-data-label">Views</p><p class="image-data-text">${l}</p></li>
  <li class="image-data"><p class="image-data-label">Likes</p><p class="image-data-text">${t}</p></li>
  <li class="image-data"><p class="image-data-label">Comments</p><p class="image-data-text">${q}</p></li>
  <li class="image-data"><p class="image-data-label">Downloads</p><p class="image-data-text">${v}</p></li>
  </ul>
        </li>
        `).join("");p.insertAdjacentHTML("beforeend",a),R.refresh()}function $(){p.innerHTML=""}function L(){h.classList.remove("is-hidden")}function u(){h.classList.add("is-hidden")}function b(){f.classList.remove("is-hidden")}function g(){f.classList.add("is-hidden")}const w=document.querySelector(".form"),E=document.querySelector('[name="search-text"]'),O=document.querySelector(".loadMoreButton");let n=1,r,d="";const S=15;async function I(o){if(o.preventDefault(),d=E.value.trim(),d===""){i.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}$(),n=1,g(),L();try{if(r=await m(d,n),u(),!r.hits||r.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(r.hits),w.reset(),Math.ceil(r.totalHits/S)>1?b():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(a){u(),i.error({message:"Something went wrong. Try again later.",position:"topRight"}),console.log("Fetch error:",a)}}async function _(){n+=1,g(),L();try{r=await m(d,n),u(),y(r.hits);const o=document.querySelector(".gallery-item");if(o){let s=o.getBoundingClientRect();window.scrollBy({top:s.height*2,left:0,behavior:"smooth"})}const a=Math.ceil(r.totalHits/S);n>=a?(g(),i.warning({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch(o){u(),i.error({message:"Error loading more images. Please try again.",position:"topRight"}),console.log("Помилка завантаження:",o)}}w.addEventListener("submit",I);O.addEventListener("click",_);
//# sourceMappingURL=index.js.map
