import{a as B,S as x,i as c}from"./assets/vendor--6n4cVRZ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const M="54715064-755e6188e76709980fdae3ed5",P="https://pixabay.com/api/";async function p(a,r){return(await B.get(P,{params:{key:M,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}const h=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".loadMoreButton");let $=new x(".gallery a",{captionsData:"alt",captionDelay:250});function L(a){const r=a.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:l,comments:q,downloads:v})=>`<li class = "gallery-item">
        <a href = "${i}" class="gallery-link">
        <img src = "${s}" alt = "${e}" class="gallery-images"/>
        </a>
       <ul class="data-list">
  <li class="image-data"><p class="image-data-label">Views</p><p class="image-data-text">${l}</p></li>
  <li class="image-data"><p class="image-data-label">Likes</p><p class="image-data-text">${t}</p></li>
  <li class="image-data"><p class="image-data-label">Comments</p><p class="image-data-text">${q}</p></li>
  <li class="image-data"><p class="image-data-label">Downloads</p><p class="image-data-text">${v}</p></li>
  </ul>
        </li>
        `).join("");h.insertAdjacentHTML("beforeend",r),$.refresh()}function O(){h.innerHTML=""}function u(){f.classList.remove("is-hidden")}function m(){f.classList.add("is-hidden")}function b(){y.classList.remove("is-hidden")}function g(){y.classList.add("is-hidden")}const w=document.querySelector(".form"),R=document.querySelector('[name="search-text"]'),E=document.querySelector(".loadMoreButton");let n=1,o,d="";const S=15;u();async function I(a){if(a.preventDefault(),d=R.value.trim(),d===""){c.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}O(),n=1,g(),u();try{if(o=await p(d,n),m(),!o.hits||o.hits.length===0){g(),u(),c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(o.hits),o.totalHits>S&&b()}catch(r){m(),c.error({message:"Something went wrong. Try again later.",position:"topRight"}),console.log("Fetch error:",r)}w.reset()}async function _(){n+=1,b();try{o=await p(d,n),L(o.hits);const a=document.querySelector(".gallery-item");if(a){let s=a.getBoundingClientRect();window.scrollBy({top:s.height*2,left:0,behavior:"smooth"})}const r=Math.ceil(o.totalHits/S);n>=r&&(g(),c.warning({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(a){console.log("Помилка завантаження:",a)}}w.addEventListener("submit",I);E.addEventListener("click",_);
//# sourceMappingURL=index.js.map
